export const bank = [
  { code: '002', label: 'BANK BRI' },
  { code: '008', label: 'BANK MANDIRI' },
  { code: '009', label: 'BANK BNI' },
  { code: '427', label: 'BANK BNI SYARIAH' },
  { code: '011', label: 'BANK DANAMON' },
  { code: '013', label: 'PERMATA BANK' },
  { code: '014', label: 'BANK BCA' },
  { code: '016', label: 'BANK BII' },
  { code: '019', label: 'BANK PANIN' },
  { code: '022', label: 'BANK NIAGA' },
  { code: '026', label: 'BANK LIPPO' },
  { code: '028', label: 'BANK NISP' },
  { code: '147', label: 'BANK MUAMALAT' },
  { code: '451', label: 'BANK SYARIAH MANDIRI' },
];
